import Head from 'next/head';
import Image from 'next/image';
import { Inter } from 'next/font/google';
import styles from '@/styles/Home.module.css';
import Link from 'next/link';
/* import { RegexComp } from './components/regexComp'; */
import React, { useState, useEffect } from 'react';
import WebsiteList from './components/WebsiteList';
import { fetchPublicSuffixList } from './utils/utils';

export default function Home() {

  const [websites, setWebsites] = useState<string[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const getWebsites = async () => {
      const { data } = await fetchPublicSuffixList();
      setWebsites(data);
      setLoading(false);
    };

    getWebsites();
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <p> COOOKIES!!</p>
          <p> Läs Readme.md</p>
          <Link href="/faq">Faq</Link>
        </div>

        <div id={styles.websiteContainer}>
          <div id={styles.websiteContainer}>
            <WebsiteList loading={loading} websites={websites} />
          </div>
        </div>
      </main>
    </>
  );
}
